### ISSUE TITLE
xdebug loaded twice?

### ISSUE THREAD

**Issue by louisremi** [MiLk/docker-php-xdebug#2]
I constantly get `Cannot load Zend OPcache - it was already loaded` messages in the console. I noticed you set  `zend_extension=/usr/local/lib/php/extensions/no-debug-non-zts-20151012/xdebug.so` twice in your Dockerfile.
I removed the directive that was adding it to `opcache.ini` and the messages stopped.
Was this repetition intentional?

**Comment by MiLk** [comment]
I will generate new images and check that opcache is not loaded twice.

The dockerfile loads xdebug and opcache.

**Comment by MiLk** [comment]
I didn't see the issue on new images.
The images are being updated on docker hub https://hub.docker.com/r/milk/php-xdebug/builds/

**Comment by louisremi** [comment]
I'll provide you a link to the image I'm using asap. In the meantime, could you explain why you are setting `zend_extension` to the same value in two different places? Do you foresee any problem if I remove one?

**Comment by MiLk** [comment]
The value is not the same. You have [xdebug](https://github.com/MiLk/docker-php-xdebug/blob/master/7.1/Dockerfile#L15) and [opcache](https://github.com/MiLk/docker-php-xdebug/blob/master/7.1/Dockerfile#L27).

**Comment by louisremi** [comment]
My bad, the problem had to do with the fact that I had two different `opcache.ini` files. It had nothing to do with xdebug, and the values are not the same.
